version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: rest_with_spring_udemy
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: